name: Online
main: se.xtralarge.online.Online
version: 1.0
author: getninjaN
commands:
   online:
      description: Shows online players in entered world
      usage: /online <world name> or /online