name: Online
main: se.xtralarge.online.Online
version: 1.1.1
author: getninjaN
commands:
   online:
      description: Displays how many players that is online vs. max players
      usage: /online
   listplayers:
      description: Displays players on the entire server and what world they are in
      usage: /listplayers or /listplayers [world name] 
